/**
 * Game State Engine - Applies actions and mutates game state
 *
 * This module handles all state transitions for the Catan game.
 */

import type {
  GameState,
  Action,
  PlayerId,
  Resources,
  ResourceType,
  Building,
  Road,
  HexId,
  VertexId,
  Player,
} from '../types/index.js'
import { BUILDING_COSTS, subtractResources, addResources, hasResources } from '../types/resources.js'
import { TERRAIN_RESOURCE } from '../types/board.js'

/**
 * Result of applying an action
 */
export interface ActionResult {
  success: boolean
  events: GameEvent[]
  error?: string
}

/**
 * Events generated by actions
 */
export type GameEvent =
  | { type: 'dice_rolled'; player: PlayerId; value: [number, number]; total: number }
  | { type: 'resources_produced'; productions: Map<PlayerId, Resources> }
  | { type: 'building_built'; player: PlayerId; buildingType: 'settlement' | 'city' | 'road'; location: string }
  | { type: 'resources_spent'; player: PlayerId; resources: Resources }
  | { type: 'dev_card_bought'; player: PlayerId; cardId: string }
  | { type: 'dev_card_played'; player: PlayerId; cardType: string }
  | { type: 'trade_completed'; from: PlayerId; to: PlayerId; gave: Resources; received: Resources }
  | { type: 'robber_moved'; player: PlayerId; from: HexId; to: HexId }
  | { type: 'resource_stolen'; thief: PlayerId; victim: PlayerId; resource: ResourceType }
  | { type: 'cards_discarded'; player: PlayerId; resources: Resources }
  | { type: 'turn_ended'; player: PlayerId }
  | { type: 'victory_points_changed'; player: PlayerId; oldVP: number; newVP: number }
  | { type: 'longest_road_changed'; oldHolder: PlayerId | null; newHolder: PlayerId | null }
  | { type: 'largest_army_changed'; oldHolder: PlayerId | null; newHolder: PlayerId | null }

/**
 * Apply an action to the game state
 */
export function applyAction(state: GameState, action: Action): ActionResult {
  const events: GameEvent[] = []

  try {
    switch (action.type) {
      case 'roll_dice':
        return applyRollDice(state, action.player)

      case 'build_settlement':
        return applyBuildSettlement(state, action.player, action.vertex)

      case 'build_city':
        return applyBuildCity(state, action.player, action.vertex)

      case 'build_road':
        return applyBuildRoad(state, action.player, action.edge)

      case 'buy_dev_card':
        return applyBuyDevCard(state, action.player)

      case 'play_dev_card':
        return applyPlayDevCard(state, action.player, action.cardId, action.params)

      case 'bank_trade':
        return applyBankTrade(state, action.player, action.offer as Resources, action.request as Resources)

      case 'move_robber':
        return applyMoveRobber(state, action.player, action.hex)

      case 'steal_resource':
        return applyStealResource(state, action.player, action.target)

      case 'discard':
        return applyDiscard(state, action.player, action.resources as Resources)

      case 'end_turn':
        return applyEndTurn(state, action.player)

      case 'propose_trade':
      case 'accept_trade':
      case 'reject_trade':
        // Trade actions are handled by the Game Master's trade system
        return { success: true, events: [] }

      default:
        return { success: false, events: [], error: `Unknown action type: ${(action as Action).type}` }
    }
  } catch (error) {
    return { success: false, events, error: String(error) }
  }
}

/**
 * Roll dice and produce resources
 */
function applyRollDice(state: GameState, player: PlayerId): ActionResult {
  const events: GameEvent[] = []

  // Roll two dice
  const die1 = Math.floor(Math.random() * 6) + 1
  const die2 = Math.floor(Math.random() * 6) + 1
  const total = die1 + die2

  state.turnState.diceRolled = true
  state.turnState.diceValue = [die1, die2]

  events.push({ type: 'dice_rolled', player, value: [die1, die2], total })

  if (total === 7) {
    // Robber activated - players with >7 cards must discard
    state.phase = 'robber_discard'
    // Check who needs to discard
    for (const [playerId, playerState] of state.players) {
      const cardCount = Object.values(playerState.resources).reduce((a, b) => a + b, 0)
      if (cardCount > 7) {
        // Player must discard half (rounded down)
        // This is tracked by playersDiscarded set
      } else {
        state.turnState.playersDiscarded.add(playerId)
      }
    }
    // If no one needs to discard, go to robber move
    if (state.turnState.playersDiscarded.size === state.players.size) {
      state.phase = 'robber_move'
    }
  } else {
    // Produce resources
    const productions = produceResources(state, total)
    if (productions.size > 0) {
      events.push({ type: 'resources_produced', productions })
    }
    state.phase = 'main'
  }

  return { success: true, events }
}

/**
 * Produce resources for a dice roll
 */
function produceResources(state: GameState, diceTotal: number): Map<PlayerId, Resources> {
  const productions = new Map<PlayerId, Resources>()

  // Find hexes with this number
  for (const hex of state.board.hexes.values()) {
    if (hex.number !== diceTotal || hex.hasRobber) continue

    const resource = TERRAIN_RESOURCE[hex.terrain]
    if (!resource) continue

    // Find buildings adjacent to this hex
    for (const building of state.board.buildings) {
      const vertex = state.board.vertices.get(building.vertex)
      if (!vertex?.adjacentHexes.includes(hex.id)) continue

      const amount = building.type === 'city' ? 2 : 1
      const player = state.players.get(building.player)
      if (!player) continue

      // Check bank has resources
      if (state.bankResources[resource] < amount) continue

      // Transfer resources
      player.resources[resource] += amount
      state.bankResources[resource] -= amount

      // Track production
      if (!productions.has(building.player)) {
        productions.set(building.player, { wood: 0, brick: 0, wheat: 0, sheep: 0, ore: 0 })
      }
      productions.get(building.player)![resource] += amount
    }
  }

  return productions
}

/**
 * Build a settlement
 */
function applyBuildSettlement(state: GameState, player: PlayerId, vertex: VertexId): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  const cost = BUILDING_COSTS.settlement

  // Deduct resources
  if (!hasResources(playerState.resources, cost)) {
    return { success: false, events, error: 'Insufficient resources' }
  }
  subtractResources(playerState.resources, cost)
  addResources(state.bankResources, cost)
  events.push({ type: 'resources_spent', player, resources: cost })

  // Place building
  const building: Building = { type: 'settlement', vertex, player }
  state.board.buildings.push(building)
  events.push({ type: 'building_built', player, buildingType: 'settlement', location: vertex })

  // Update VP
  const oldVP = playerState.publicVictoryPoints
  playerState.publicVictoryPoints += 1
  playerState.totalVictoryPoints += 1
  events.push({ type: 'victory_points_changed', player, oldVP, newVP: playerState.publicVictoryPoints })

  state.turnState.buildCount++

  return { success: true, events }
}

/**
 * Build a city (upgrade settlement)
 */
function applyBuildCity(state: GameState, player: PlayerId, vertex: VertexId): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  const cost = BUILDING_COSTS.city

  // Deduct resources
  if (!hasResources(playerState.resources, cost)) {
    return { success: false, events, error: 'Insufficient resources' }
  }
  subtractResources(playerState.resources, cost)
  addResources(state.bankResources, cost)
  events.push({ type: 'resources_spent', player, resources: cost })

  // Upgrade settlement to city
  const building = state.board.buildings.find(b => b.vertex === vertex && b.player === player)
  if (!building || building.type !== 'settlement') {
    return { success: false, events, error: 'No settlement at this location' }
  }
  building.type = 'city'
  events.push({ type: 'building_built', player, buildingType: 'city', location: vertex })

  // Update VP (+1 because city is worth 2, settlement was worth 1)
  const oldVP = playerState.publicVictoryPoints
  playerState.publicVictoryPoints += 1
  playerState.totalVictoryPoints += 1
  events.push({ type: 'victory_points_changed', player, oldVP, newVP: playerState.publicVictoryPoints })

  state.turnState.buildCount++

  return { success: true, events }
}

/**
 * Build a road
 */
function applyBuildRoad(state: GameState, player: PlayerId, edge: string): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  const cost = BUILDING_COSTS.road

  // Deduct resources (unless road building dev card effect is active)
  if (state.activeEffect.type !== 'road_building') {
    if (!hasResources(playerState.resources, cost)) {
      return { success: false, events, error: 'Insufficient resources' }
    }
    subtractResources(playerState.resources, cost)
    addResources(state.bankResources, cost)
    events.push({ type: 'resources_spent', player, resources: cost })
  } else {
    // Using road building card
    state.activeEffect.roadsRemaining--
    if (state.activeEffect.roadsRemaining <= 0) {
      state.activeEffect = { type: 'none' }
    }
  }

  // Place road
  const road: Road = { edge, player }
  state.board.roads.push(road)
  events.push({ type: 'building_built', player, buildingType: 'road', location: edge })

  // Check longest road
  const longestRoadEvent = checkLongestRoad(state)
  if (longestRoadEvent) events.push(longestRoadEvent)

  state.turnState.buildCount++

  return { success: true, events }
}

/**
 * Buy a development card
 */
function applyBuyDevCard(state: GameState, player: PlayerId): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  if (state.devCardDeck.length === 0) {
    return { success: false, events, error: 'No development cards remaining' }
  }

  const cost = BUILDING_COSTS.devCard

  if (!hasResources(playerState.resources, cost)) {
    return { success: false, events, error: 'Insufficient resources' }
  }
  subtractResources(playerState.resources, cost)
  addResources(state.bankResources, cost)
  events.push({ type: 'resources_spent', player, resources: cost })

  // Draw card
  const cardId = state.devCardDeck.pop()!
  const cardTypes = ['knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'knight', 'road_building', 'road_building', 'year_of_plenty', 'year_of_plenty', 'monopoly', 'monopoly', 'victory_point', 'victory_point', 'victory_point', 'victory_point', 'victory_point'] as const
  const cardType = cardTypes[Math.floor(Math.random() * cardTypes.length)]!

  playerState.devCards.push({
    id: cardId,
    type: cardType,
    turnBought: state.turn,
    played: false,
  })

  state.turnState.devCardsBought.push(cardId)
  events.push({ type: 'dev_card_bought', player, cardId })

  // If VP card, add to total (but not public)
  if (cardType === 'victory_point') {
    playerState.totalVictoryPoints += 1
  }

  return { success: true, events }
}

/**
 * Play a development card
 */
function applyPlayDevCard(
  state: GameState,
  player: PlayerId,
  cardId: string,
  params?: { resources?: [ResourceType, ResourceType]; resource?: ResourceType }
): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  const card = playerState.devCards.find(c => c.id === cardId)
  if (!card) return { success: false, events, error: 'Card not found' }
  if (card.played) return { success: false, events, error: 'Card already played' }
  if (card.turnBought === state.turn) return { success: false, events, error: 'Cannot play card bought this turn' }
  if (state.turnState.devCardPlayed && card.type !== 'victory_point') {
    return { success: false, events, error: 'Already played a dev card this turn' }
  }

  card.played = true
  if (card.type !== 'victory_point') {
    state.turnState.devCardPlayed = true
  }

  events.push({ type: 'dev_card_played', player, cardType: card.type })

  switch (card.type) {
    case 'knight':
      playerState.knightsPlayed++
      state.phase = 'robber_move'
      // Check largest army
      const armyEvent = checkLargestArmy(state)
      if (armyEvent) events.push(armyEvent)
      break

    case 'road_building':
      state.activeEffect = { type: 'road_building', roadsRemaining: 2 }
      break

    case 'year_of_plenty':
      if (params?.resources) {
        for (const resource of params.resources) {
          if (state.bankResources[resource] > 0) {
            playerState.resources[resource]++
            state.bankResources[resource]--
          }
        }
      }
      break

    case 'monopoly':
      if (params?.resource) {
        const resource = params.resource
        for (const [otherId, otherPlayer] of state.players) {
          if (otherId !== player) {
            const amount = otherPlayer.resources[resource]
            otherPlayer.resources[resource] = 0
            playerState.resources[resource] += amount
          }
        }
      }
      break

    case 'victory_point':
      // VP already added when card was bought
      break
  }

  return { success: true, events }
}

/**
 * Trade with bank (4:1 or port rates)
 */
function applyBankTrade(state: GameState, player: PlayerId, offer: Resources, request: Resources): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  // Calculate required ratio (simplified - would check ports)
  const ratio = 4

  // Validate trade
  const offerTotal = Object.values(offer).reduce((a, b) => a + b, 0)
  const requestTotal = Object.values(request).reduce((a, b) => a + b, 0)

  if (offerTotal !== ratio * requestTotal) {
    return { success: false, events, error: `Must offer ${ratio} resources for each 1 requested` }
  }

  if (!hasResources(playerState.resources, offer)) {
    return { success: false, events, error: 'Insufficient resources to offer' }
  }

  if (!hasResources(state.bankResources, request)) {
    return { success: false, events, error: 'Bank does not have requested resources' }
  }

  // Execute trade
  subtractResources(playerState.resources, offer)
  addResources(state.bankResources, offer)
  addResources(playerState.resources, request)
  subtractResources(state.bankResources, request)

  events.push({ type: 'trade_completed', from: player, to: 'bank', gave: offer, received: request })
  state.turnState.tradeCount++

  return { success: true, events }
}

/**
 * Move the robber
 */
function applyMoveRobber(state: GameState, player: PlayerId, hex: HexId): ActionResult {
  const events: GameEvent[] = []

  const oldHex = state.board.robberHex
  if (hex === oldHex) {
    return { success: false, events, error: 'Must move robber to a different hex' }
  }

  // Move robber
  const oldHexObj = state.board.hexes.get(oldHex)
  const newHexObj = state.board.hexes.get(hex)
  if (oldHexObj) oldHexObj.hasRobber = false
  if (newHexObj) newHexObj.hasRobber = true
  state.board.robberHex = hex

  events.push({ type: 'robber_moved', player, from: oldHex, to: hex })

  state.turnState.robberMoved = true
  state.phase = 'robber_steal'

  return { success: true, events }
}

/**
 * Steal a resource after moving robber
 */
function applyStealResource(state: GameState, player: PlayerId, target: PlayerId): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  const targetState = state.players.get(target)

  if (!playerState || !targetState) {
    return { success: false, events, error: 'Player not found' }
  }

  // Get target's resources
  const availableResources: ResourceType[] = []
  for (const [resource, amount] of Object.entries(targetState.resources) as [ResourceType, number][]) {
    for (let i = 0; i < amount; i++) {
      availableResources.push(resource)
    }
  }

  if (availableResources.length === 0) {
    // No resources to steal
    state.phase = 'main'
    return { success: true, events }
  }

  // Steal random resource
  const stolenResource = availableResources[Math.floor(Math.random() * availableResources.length)]!
  targetState.resources[stolenResource]--
  playerState.resources[stolenResource]++

  events.push({ type: 'resource_stolen', thief: player, victim: target, resource: stolenResource })
  state.phase = 'main'

  return { success: true, events }
}

/**
 * Discard cards (when over 7 on a 7 roll)
 */
function applyDiscard(state: GameState, player: PlayerId, resources: Resources): ActionResult {
  const events: GameEvent[] = []
  const playerState = state.players.get(player)
  if (!playerState) return { success: false, events, error: 'Player not found' }

  const cardCount = Object.values(playerState.resources).reduce((a, b) => a + b, 0)
  const requiredDiscard = Math.floor(cardCount / 2)
  const discardCount = Object.values(resources).reduce((a, b) => a + b, 0)

  if (discardCount !== requiredDiscard) {
    return { success: false, events, error: `Must discard exactly ${requiredDiscard} cards` }
  }

  if (!hasResources(playerState.resources, resources)) {
    return { success: false, events, error: 'Cannot discard more resources than you have' }
  }

  subtractResources(playerState.resources, resources)
  addResources(state.bankResources, resources)
  state.turnState.playersDiscarded.add(player)

  events.push({ type: 'cards_discarded', player, resources })

  // Check if all players have discarded
  if (state.turnState.playersDiscarded.size === state.players.size) {
    state.phase = 'robber_move'
  }

  return { success: true, events }
}

/**
 * End the current turn
 */
function applyEndTurn(state: GameState, player: PlayerId): ActionResult {
  const events: GameEvent[] = []

  events.push({ type: 'turn_ended', player })

  // Advance to next player
  state.currentPlayerIndex = (state.currentPlayerIndex + 1) % state.turnOrder.length
  if (state.currentPlayerIndex === 0) {
    state.turn++
  }

  // Reset turn state
  state.phase = 'pre_roll'
  state.turnState = {
    diceRolled: false,
    diceValue: null,
    buildCount: 0,
    tradeCount: 0,
    devCardPlayed: false,
    devCardsBought: [],
    playersDiscarded: new Set(),
    robberMoved: false,
    resourcesAtTurnStart: new Map(),
    resourcesProduced: new Map(),
  }

  // Copy current resources for tracking
  for (const [id, p] of state.players) {
    state.turnState.resourcesAtTurnStart.set(id, { ...p.resources })
  }

  state.activeEffect = { type: 'none' }

  return { success: true, events }
}

/**
 * Check and update longest road
 */
function checkLongestRoad(state: GameState): GameEvent | null {
  // Simplified - would need actual road length calculation
  const roadCounts = new Map<PlayerId, number>()
  for (const road of state.board.roads) {
    roadCounts.set(road.player, (roadCounts.get(road.player) ?? 0) + 1)
  }

  let longest = state.longestRoadLength
  let holder = state.longestRoadPlayer

  for (const [player, count] of roadCounts) {
    if (count >= 5 && count > longest) {
      longest = count
      holder = player
    }
  }

  if (holder !== state.longestRoadPlayer) {
    const oldHolder = state.longestRoadPlayer
    // Update VP
    if (oldHolder) {
      const old = state.players.get(oldHolder)
      if (old) {
        old.publicVictoryPoints -= 2
        old.totalVictoryPoints -= 2
      }
    }
    if (holder) {
      const newP = state.players.get(holder)
      if (newP) {
        newP.publicVictoryPoints += 2
        newP.totalVictoryPoints += 2
      }
    }
    state.longestRoadPlayer = holder
    state.longestRoadLength = longest
    return { type: 'longest_road_changed', oldHolder, newHolder: holder }
  }

  return null
}

/**
 * Check and update largest army
 */
function checkLargestArmy(state: GameState): GameEvent | null {
  let largest = state.largestArmySize
  let holder = state.largestArmyPlayer

  for (const [player, playerState] of state.players) {
    if (playerState.knightsPlayed >= 3 && playerState.knightsPlayed > largest) {
      largest = playerState.knightsPlayed
      holder = player
    }
  }

  if (holder !== state.largestArmyPlayer) {
    const oldHolder = state.largestArmyPlayer
    // Update VP
    if (oldHolder) {
      const old = state.players.get(oldHolder)
      if (old) {
        old.publicVictoryPoints -= 2
        old.totalVictoryPoints -= 2
      }
    }
    if (holder) {
      const newP = state.players.get(holder)
      if (newP) {
        newP.publicVictoryPoints += 2
        newP.totalVictoryPoints += 2
      }
    }
    state.largestArmyPlayer = holder
    state.largestArmySize = largest
    return { type: 'largest_army_changed', oldHolder, newHolder: holder }
  }

  return null
}
